// HK-OI quality-control + analytics report -> reports/report.md + stdout JSON
import { DatabaseSync } from "node:sqlite";
import { mkdirSync, writeFileSync } from "node:fs";

const db = new DatabaseSync("exports/ontology.db");
const q = (sql) => db.prepare(sql).all();
const q1 = (sql) => db.prepare(sql).get();
const L = []; const line = (s="") => L.push(s);

const totalNodes = q1("SELECT COUNT(*) c FROM nodes").c;
const totalRels = q1("SELECT COUNT(*) c FROM relations").c;
const withMetrics = q1("SELECT COUNT(*) c FROM nodes WHERE metrics IS NOT NULL").c;

line("# HK-OI Ontology Report");
line(); line("Generated: " + new Date().toISOString());
line(); line("## 1. Summary");
line();
line(`- **Nodes**: ${totalNodes}  (with metrics: ${withMetrics})`);
line(`- **Relations**: ${totalRels}`);
line();
line("### By universe");
line(); line("| universe | nodes |"); line("|---|---|");
for (const r of q("SELECT universe, COUNT(*) c FROM nodes GROUP BY universe ORDER BY c DESC")) line(`| ${r.universe} | ${r.c} |`);
line();
line("### By level");
line(); line("| level | nodes |"); line("|---|---|");
for (const r of q("SELECT level, COUNT(*) c FROM nodes GROUP BY level ORDER BY level")) line(`| L${r.level} | ${r.c} |`);
line();
line("### By type");
line(); line("| type | nodes |"); line("|---|---|");
for (const r of q("SELECT type, COUNT(*) c FROM nodes GROUP BY type ORDER BY c DESC")) line(`| ${r.type} | ${r.c} |`);
line();

// ---- metrics analytics ----
line("## 2. Civilization Metrics");
line();
line("### Growth trajectory (recent)");
line(); line("| growth | nodes |"); line("|---|---|");
for (const r of q("SELECT json_extract(metrics,'$.growth') g, COUNT(*) c FROM nodes WHERE metrics IS NOT NULL GROUP BY g ORDER BY c DESC")) line(`| ${r.g} | ${r.c} |`);
line();
line("### Historical significance");
line(); line("| level | nodes |"); line("|---|---|");
for (const r of q("SELECT json_extract(metrics,'$.historical_significance') h, COUNT(*) c FROM nodes WHERE metrics IS NOT NULL GROUP BY h ORDER BY c DESC")) line(`| ${r.h} | ${r.c} |`);
line();
line("### Economic vs cultural weight (NOT ranked by economics)");
line(); line("| economic_weight | cultural_weight | nodes |"); line("|---|---|---|");
for (const r of q("SELECT json_extract(metrics,'$.economic_weight') ew, json_extract(metrics,'$.cultural_weight') cw, COUNT(*) c FROM nodes WHERE metrics IS NOT NULL GROUP BY ew,cw ORDER BY c DESC LIMIT 20")) line(`| ${r.ew} | ${r.cw} | ${r.c} |`);
line();
line("### Fields where cultural weight exceeds economic weight (culture-first nodes)");
line();
for (const r of q(`SELECT name, json_extract(metrics,'$.cultural_weight') cw, json_extract(metrics,'$.economic_weight') ew FROM nodes WHERE metrics IS NOT NULL AND json_extract(metrics,'$.cultural_weight') IN ('very_high','high') AND json_extract(metrics,'$.economic_weight') IN ('negligible','low') LIMIT 40`)) line(`- ${r.name} (cultural ${r.cw} / economic ${r.ew})`);
line();
line("### Data confidence (distribution)");
line(); line("| confidence | nodes |"); line("|---|---|");
for (const r of q("SELECT json_extract(metrics,'$.confidence') cf, COUNT(*) c FROM nodes WHERE metrics IS NOT NULL GROUP BY cf ORDER BY cf")) line(`| ${r.cf} | ${r.c} |`);
line();
line("### Methodology provenance");
line(); line("| method | nodes |"); line("|---|---|");
for (const r of q("SELECT json_extract(metrics,'$.method') m, COUNT(*) c FROM nodes WHERE metrics IS NOT NULL GROUP BY m ORDER BY c DESC")) line(`| ${r.m} | ${r.c} |`);
line();

// ---- QC ----
line("## 3. Quality Control");
line();
line("### A. Completeness — universes");
line(); line("| universe | nodes | status |"); line("|---|---|---|");
for (const r of q("SELECT universe, COUNT(*) c FROM nodes WHERE type != 'UNIVERSE' GROUP BY universe ORDER BY c")) line(`| ${r.universe} | ${r.c} | ${r.c < 30 ? "⚠ under-developed" : "ok"} |`);
line();
line("### B. Granularity — max depth per universe");
line(); line("| universe | max level |"); line("|---|---|");
for (const r of q("SELECT universe, MAX(level) m FROM nodes GROUP BY universe ORDER BY m DESC")) line(`| ${r.universe} | ${r.m} |`);
line();
line("### C. Overlap — cross-link relation types");
line(); line("| relation | count |"); line("|---|---|");
for (const r of q("SELECT relation, COUNT(*) c FROM relations GROUP BY relation ORDER BY c DESC")) line(`| ${r.relation} | ${r.c} |`);
line();
line("### D. Duplication — identical names");
line();
const dups = q("SELECT name, COUNT(*) c FROM nodes GROUP BY name HAVING c > 1 ORDER BY c DESC LIMIT 30");
line(`Potential duplicate names: ${dups.length}`);
for (const r of dups) line(`- ${r.name} (x${r.c})`);
line();
line("### F. Cultural bias — region-specific nodes");
line(`- region-specific (global=false): ${q1("SELECT COUNT(*) c FROM nodes WHERE global=0").c}`);
line();
line("### G. Historical — extinct categories");
line(`- historical: ${q1("SELECT COUNT(*) c FROM nodes WHERE historical=1").c}`);
line();

// ---- analytics ----
line("## 4. Analytics (sample questions)");
line();
line("### Q. 数学有哪些领域?");
const mathSub = q("WITH RECURSIVE sub(id) AS (SELECT 'HK.mathematics' UNION ALL SELECT n.id FROM nodes n JOIN sub s ON n.parent=s.id) SELECT id,name,level FROM nodes WHERE id IN (SELECT id FROM sub) AND id != 'HK.mathematics' ORDER BY level,id");
line(`- count: ${mathSub.length}`);
line();
line("### Q. 半导体产业有哪些环节?");
const semi = q("WITH RECURSIVE sub(id) AS (SELECT 'ind.manufacturing.semiconductors' UNION ALL SELECT n.id FROM nodes n JOIN sub s ON n.parent=s.id) SELECT name,level FROM nodes WHERE id IN (SELECT id FROM sub) ORDER BY level,name");
line(`- count: ${semi.length}`);
line();
line("### Q. 有哪些已经消失的职业?");
const hist = q("SELECT name FROM nodes WHERE historical=1 AND universe='HISTORICAL_OCCUPATIONS' ORDER BY name LIMIT 30");
line(`- count: ${q1("SELECT COUNT(*) c FROM nodes WHERE historical=1 AND universe='HISTORICAL_OCCUPATIONS'").c}`);
for (const r of hist) line(`- ${r.name}`);
line();
line("### Q. 一个 GPU 公司属于哪些产业? (graph reach from GPU)");
for (const r of q("SELECT r.relation, n.name FROM relations r JOIN nodes n ON n.id=r.target WHERE r.source='TECH.information_technology.computing.computer_hardware.processor_technology.graphics_processing_unit'")) line(`- ${r.relation} ${r.name}`);
line();
line("### Q. 哪些职业跨越最多知识领域? (occupation -> knowledge links)");
for (const r of q("SELECT n.name, COUNT(*) d FROM relations r JOIN nodes n ON n.id=r.source WHERE n.type='OCCUPATION' AND r.target LIKE 'HK.%' GROUP BY n.id ORDER BY d DESC LIMIT 15")) line(`- ${r.name}: ${r.d}`);
line();
line("### Q. 哪些产业拥有最多不同职业? (industry -> occupation links)");
for (const r of q("SELECT n.name, COUNT(*) d FROM relations r JOIN nodes n ON n.id=r.source WHERE n.type IN ('INDUSTRY','SECTOR') AND r.target LIKE 'OCC.%' GROUP BY n.id ORDER BY d DESC LIMIT 15")) line(`- ${r.name}: ${r.d}`);
line();
line("### Q. 关联最多的节点 (most cross-linked)");
line("| node | degree |"); line("|---|---|");
for (const r of q("SELECT n.name, COUNT(*) d FROM relations r JOIN nodes n ON n.id=r.source GROUP BY n.id ORDER BY d DESC LIMIT 20")) line(`| ${r.name} | ${r.d} |`);
line();
line("## 5. Method note");
line();
line("Metrics are order-of-magnitude estimates (method: model_estimate / expert_judgment / qualitative) with explicit confidence in [0,1]. Population/economy are omitted (not 'unknown') where a node is not a human activity (products, organizations). No single ranking is imposed — economic_weight and cultural_weight are kept as separate orthogonal dimensions.");

mkdirSync("reports", { recursive: true });
writeFileSync("reports/report.md", L.join("\n"));
db.close();
console.log(JSON.stringify({ totalNodes, totalRels, withMetrics, wrote: "reports/report.md" }));
